# Generated by Django 4.0.4 on 2022-05-10 08:44

from django.db import migrations, models
import django.db.models.deletion
import shipping.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resi', models.CharField(default=shipping.utils.create_new_ref_number, editable=False, max_length=10, unique=True)),
                ('nama_barang', models.CharField(max_length=255)),
                ('nama_pengirim', models.CharField(max_length=255)),
                ('alamat_pengirim', models.TextField()),
                ('nama_tujuan', models.CharField(max_length=255)),
                ('alamat_tujuan', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
                ('berat', models.IntegerField()),
                ('bayar', models.IntegerField()),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping.category')),
            ],
            options={
                'verbose_name_plural': 'Shipping',
            },
        ),
    ]
