# Generated by Django 4.0.4 on 2022-05-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_remove_category_slug_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='kategori',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
