# Generated by Django 4.0.4 on 2022-05-11 23:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0004_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifPerKilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harga', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Tarif per Kilo',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Category'},
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='bayar',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='created',
        ),
        migrations.AddField(
            model_name='shipping',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
