# Generated by Django 4.0.4 on 2022-05-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0005_tarifperkilo_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifperkilo',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tarifperkilo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
