# Generated by Django 4.0.4 on 2022-05-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0007_shipping_tarif_per_kilo'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='tarif_per_kilo',
            field=models.IntegerField(),
        ),
    ]
